### ISSUE TITLE
Firefox now support Web-MIDI

### ISSUE THREAD

**Issue by nodens** [trotttrotttrott/es9-mixer#1]
Hi,

I tried with Firefox (117) since it's supposed to support web-midi now.

I had trouble figuring out which port I had to use, though, while it's working fine on the config tool (this part at least, there are other issues). I managed to make the app happy, but it never receives the mix when it asks:

```

ES-9 MIDI input ID: 7MNkgPGbvs0gYLlXnEcWiLEfJAWgxbARlIoeeMneRw8=
ES-9 MIDI output ID: gWnJ719YPEpHaD+hUdIA72N7w/SK6dBexNFC0gnHxoQ=

5:00:41 PM: Requesting mix
```

Possibly this is because I couldn't find the proper port for output.

It would be great to have this working in Firefox too ! I only use chromium (or chrome) for midi/DRM duty… ;)

anyway, thanks for this nice app! If you ever wanna have a try at revamping the config tool to make it more user friendly, I'd be glad to help (not with js code, though, except trivial stuff…) ;)

**Comment by trotttrotttrott** [comment]
Sounds like we're all good now! https://www.modwiggler.com/forum/viewtopic.php?p=4064852&sid=45f8b044670856e095bda42666c0fc7a#p4064852

My guess is the dependency update [here](https://github.com/trotttrotttrott/es9-mixer/pull/3) fixed things.

**Comment by nodens** [comment]
indeed, and I should have remembered to comment here as well ;)
